### ISSUE TITLE
Did you mean Thermostat, not sensor?

### ISSUE THREAD

**Issue by jmccausland** [sbdobrescu/SmartThings#1]
line 421-423 probably should be using the "thermostat" variable, not the "sensor"

**Comment by sbdobrescu** [comment]
Good catch, I am using my thermostat as sensor, so I didn't realize it. Thanks!

**Comment by jmccausland** [comment]
Forgot to mention this was for the "ZWave Thermostat Director".  I'm glad I found it here because with a little modifications I automated the balancing of the temperature in my kids rooms.  I have 4 bedrooms in zone 2 and the thermostat is in the forth bedroom which we don't use.  I wanted to close it off to be more efficient and balance out the kids rooms.  As you can see in my google sheet the temps in each room varied quite a bit at times (A).  I installed Keen Home Smart Vents and use ScheduleRoomTemp app to keep each room from overheating.  The middle (B) is where I installed the vents and manually controlled the thermostat.  The last third of the graph (C) is where I finished things off with a modified version of the ZWave Thermostat Director and shut the thermostat room off from heat completely.  I changed the input sensor to multiple and I worked off the min temp of the list (using 2nd and 3rd room 4in1Zooz sensors).  As you can see I had an issue with it properly communicating with my CT-30 ZWave Thermostat until I put pauses between each thermostat set function.  It would only take the first command without the pauses but in the end it is now pretty consistent. Thanks!

![image](https://cloud.githubusercontent.com/assets/5815558/20645455/e3df3048-b42c-11e6-804a-14bd8c8a71bd.png)

**Comment by sbdobrescu** [comment]
Nice work! Would you like to merge your changes? Your set up is identical to mine, except that my t-stat is in the middle of my 4 bedrooms....

**Comment by sbdobrescu** [comment]
issues is now fixed. Thanks for reporting it....
